"""empty message

Revision ID: d6b749e23b73
Revises: 4cb363ad8759
Create Date: 2025-07-29 01:51:24.474129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6b749e23b73'
down_revision = '4cb363ad8759'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url', sa.String(length=255), nullable=True))

    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.drop_column('url')

    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.drop_column('url')

    # ### end Alembic commands ###
